spring:
  config:
    import: optional:application-secrets.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/playlist_tracker
    username: postgres
    password: postgres   # change if your local Postgres password differs

  jpa:
    hibernate:
      ddl-auto: update     # auto-creates/updates tables from entities (fine for dev, never for prod)
    show-sql: true          # logs SQL to console — helpful while learning, turn off later if noisy
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope:
              - email
              - profile


  logging:
    level:
      com.vidhan152.playlistTracker: DEBUG
      org.springframework.web.client: WARN

youtube:
  api:
    key: ${google.youtube-api-key}
    base-url: https://www.googleapis.com/youtube/v3

server:
  port: 8080